### ISSUE TITLE
Maybe mention in README this only flattens depth=1

### ISSUE THREAD

**Issue by elidoran** [75lb/reduce-flatten#1]
For example, it wouldn't completely flatten `[1, [2, [3, 4, 5], 6], 7, 8, 9]`.

I copied your test and edited it to a depth=2 where it'll fail.

```javascript
tom.test('flatten depth=2', function () {
  const numbers = [1, [2, [3, 4]], 5]  
  const result = numbers.reduce(flatten, [])
  a.deepStrictEqual(result, [1, 2, 3, 4, 5])})
```

It's likely that's by design, I am just thinking maybe it'd be a good to mention that in the docs.

**Comment by 75lb** [comment]
hi, does the built-in .flat() method meet your needs?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

**Comment by elidoran** [comment]
Thank you for replying, and for providing info complete with a link. Very considerate.

I'm good on array flattening tho. I just thought I'd mention it in the unlikely case you hadn't realized it wouldn't be obvious to others that it's only for depth=1. A "just in case you hadn't noted it consciously" thing.

While I have your attention tho, aside from `array.flat(1)`, the reducer for depth=1 is also the same as doing `array.flatMap(e => e)` and `[].concat(...array)`.

Also, the builtin Array.flat() function is amazingly slow. Nearly all other implementations are faster, including your reducer (which is likely several times faster if not a full order-of-magnitude faster).

Anyway, feel free to close this issue as I only submitted it in case it was a helpful thought about the README. Thank you.

**Comment by 75lb** [comment]
Interesting to hear the built-in `flat()` method is slow, however there is plenty of time for the JS engines to fix that.. most users won't care.. 

I'm about the deprecate this module and archive the repo as superceded by `.flat()` 👍
